Repository Encore-Server/Encore.1, pull requests merged in 2025-03, with the labels that each got.

#126 Removes spells clothes_req, fixes psicross spawn, adds wood amulets
  code/__DEFINES/tools.dm
  code/datums/gods/_patron.dm
  code/datums/gods/patrons/all_aspect.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/infinite_guns.dm
  code/modules/spells/spell_types/lightning.dm
  code/modules/spells/spell_types/rod_form.dm
  code/modules/spells/spell_types/the_traps.dm
  code/modules/spells/spell_types/touch_attacks.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/surgery/_surgery_step.dm
  code/modules/surgery/surgeries_hearth/cure_rot.dm
  html/changelogs/doxxmedearly - clothesnamulets.yml
  icons/roguetown/clothing/neck.dmi
  modular_azurepeak/code/datums/loadout.dm
Labels: Spriting, Balance

#128 Fort Hellwatch
  _maps/map_files/domotan/domotan_south.dmm
  code/game/area/roguetownareas.dm
  html/changelogs/furrycactus - fort_hellwatch.yml
Labels: Mapping

#129 Give Court Magi Librarium access and make dungeon doors manor access
  _maps/map_files/domotan/domotan.dmm
  code/game/objects/items/rogueitems/keyrings.dm
Labels: Mapping

#131 Fixes Knight Titles Only Applying on Latejoin
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  html/changelogs/doxxmedearly - knighttitles.yml
Labels: Balance

#132 maps in the mail master
  _maps/map_files/domotan/domotan.dmm
Labels: Mapping

#134 Removes arcane from shirleighs, destroys gender
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: Balance

#135 Map QoL Changes - Clothing, armory
  _maps/map_files/domotan/domotan.dmm
  html/changelogs/peppermint-qolmap.yml
Labels: Mapping

#138 Iron spoons and forks can be used
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  modular/Neu_Food/code/NeuFood.dm
Labels: Mapping

#142 Fixes Chair Transmutation
  code/game/objects/structures/beds_chairs/roguechair.dm
  icons/roguetown/items/chairs.dmi
Labels: Spriting

#146 Give Court Magicians Lightning Bolt
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
Labels: Balance

#150 Fixes adjust_spellpoints runtimes
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: Balance

#151 East Domotan and Mount Miracle
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/templates/forest/med_forest_fishing_pond.dmm
  _maps/map_files/templates/forest/med_forest_huntingshack.dmm
  _maps/map_files/templates/forest/small_forest_goblin_camp.dmm
  _maps/map_files/templates/forest/small_forest_outhouse.dmm
  _maps/map_files/templates/forest/small_forest_pond.dmm
  _maps/map_files/templates/forest/small_forest_shack.dmm
  _maps/map_files/templates/hell/hell_basic_1.dmm
  _maps/map_files/templates/hell/hell_basic_2.dmm
  _maps/map_files/templates/hell/hell_basic_3.dmm
  _maps/map_files/templates/hell/hell_basic_4.dmm
  _maps/map_files/templates/mountain/med_mountain_fishing_pond.dmm
  _maps/map_files/templates/mountain/med_mountain_goblin_outpost.dmm
  _maps/map_files/templates/mountain/med_mountain_huntingshack.dmm
  _maps/map_files/templates/mountain/small_mountain_goblin_camp.dmm
  _maps/map_files/templates/mountain/small_mountain_outhouse.dmm
  _maps/map_files/templates/mountain/small_mountain_pond.dmm
  _maps/map_files/templates/mountain/small_mountain_shack.dmm
  _maps/map_files/templates/snow/med_snow_armory.dmm
  _maps/map_files/templates/snow/med_snow_barracks.dmm
  _maps/map_files/templates/snow/med_snow_battlefield.dmm
  _maps/map_files/templates/snow/med_snow_cellar.dmm
  _maps/map_files/templates/snow/med_snow_church.dmm
  _maps/map_files/templates/snow/med_snow_crypt.dmm
  _maps/map_files/templates/snow/med_snow_farm.dmm
  _maps/map_files/templates/snow/med_snow_fishing_pond.dmm
  _maps/map_files/templates/snow/med_snow_forge.dmm
  _maps/map_files/templates/snow/med_snow_hotspring.dmm
  _maps/map_files/templates/snow/med_snow_huntingshack.dmm
  _maps/map_files/templates/snow/med_snow_leviathan.dmm
  _maps/map_files/templates/snow/med_snow_lodge.dmm
  _maps/map_files/templates/snow/med_snow_moundhome.dmm
  _maps/map_files/templates/snow/med_snow_pond.dmm
  _maps/map_files/templates/snow/med_snow_quarry.dmm
  _maps/map_files/templates/snow/small_snow_effigy.dmm
  _maps/map_files/templates/snow/small_snow_goblin_camp.dmm
  _maps/map_files/templates/snow/small_snow_outhouse.dmm
  _maps/map_files/templates/snow/small_snow_pond.dmm
  _maps/map_files/templates/snow/small_snow_shack.dmm
  _maps/map_files/templates/snow/small_snow_trollden.dmm
  _maps/map_files/templates/snow/small_snow_watchpost.dmm
  _maps/map_files/templates/snow/small_snow_wolfden.dmm
  _maps/templates/forest.dm
  _maps/templates/hell.dm
  _maps/templates/mountain.dm
  _maps/templates/snow.dm
  code/game/area/roguetownareas.dm
  code/game/turfs/closed/wall/roguewalls.dm
  code/modules/roguetown/mapgen/east.dm
  icons/turf/walls/blue_mossy.dmi
  icons/turf/walls/craftstone.dmi
  icons/turf/walls/decostone.dmi
  roguetown.dme
Labels: Spriting, Mapping

#162 Mt Miracle update fixes and church tweak
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/templates/forest.dm
  code/game/area/roguetownareas.dm
  code/modules/roguetown/mapgen/east.dm
  icons/turf/roguefloor.dmi
Labels: Spriting, Mapping

#164 Fixes more double tiles in east domotan
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/templates/forest/med_forest_fishing_pond.dmm
  _maps/map_files/templates/forest/med_forest_huntingshack.dmm
  _maps/map_files/templates/forest/small_forest_goblin_camp.dmm
  _maps/map_files/templates/forest/small_forest_outhouse.dmm
  _maps/map_files/templates/forest/small_forest_shack.dmm
  _maps/map_files/templates/mountain/med_mountain_fishing_pond.dmm
  _maps/map_files/templates/mountain/med_mountain_goblin_outpost.dmm
  _maps/map_files/templates/mountain/med_mountain_huntingshack.dmm
  _maps/map_files/templates/mountain/small_mountain_goblin_camp.dmm
  _maps/map_files/templates/mountain/small_mountain_outhouse.dmm
  _maps/map_files/templates/mountain/small_mountain_shack.dmm
  _maps/map_files/templates/snow/med_snow_armory.dmm
  _maps/map_files/templates/snow/med_snow_barracks.dmm
  _maps/map_files/templates/snow/med_snow_cellar.dmm
  _maps/map_files/templates/snow/med_snow_church.dmm
  _maps/map_files/templates/snow/med_snow_crypt.dmm
  _maps/map_files/templates/snow/med_snow_farm.dmm
  _maps/map_files/templates/snow/med_snow_fishing_pond.dmm
  _maps/map_files/templates/snow/med_snow_forge.dmm
  _maps/map_files/templates/snow/med_snow_hotspring.dmm
  _maps/map_files/templates/snow/med_snow_huntingshack.dmm
  _maps/map_files/templates/snow/med_snow_lodge.dmm
  _maps/map_files/templates/snow/med_snow_moundhome.dmm
  _maps/map_files/templates/snow/med_snow_quarry.dmm
  _maps/map_files/templates/snow/small_snow_goblin_camp.dmm
  _maps/map_files/templates/snow/small_snow_outhouse.dmm
  _maps/map_files/templates/snow/small_snow_shack.dmm
  _maps/map_files/templates/snow/small_snow_trollden.dmm
  _maps/map_files/templates/snow/small_snow_watchpost.dmm
  _maps/map_files/templates/snow/small_snow_wolfden.dmm
  _maps/templates/snow.dm
  _maps/templates/template_helpers.dm
  roguetown.dme
Labels: Mapping

#168 Readds arcane skill to shirleighs
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: Balance

#171 Fort Hellwatch Difficulty Buff
  _maps/map_files/domotan/domotan_south.dmm
  html/changelogs/furrycactus - fort_hellwatch_buff.yml
Labels: Mapping

#170 Warden, Bog Master, and Garrison Reworks
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
  code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  html/changelogs/furrycactus - wardens_tweak.yml
Labels: Balance

#174 Unlocks Inn Backroom
  _maps/map_files/domotan/domotan.dmm
  html/changelogs/furrycactus - unlocks_inn_backroom.yml
Labels: Mapping

#179 v1.0.9rev3
  _maps/map_files/domotan/domotan.dmm
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
  code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/roguetown/roguecrafting/turfs.dm
  html/changelogs/furrycactus - twig_floor_fix.yml
  html/changelogs/furrycactus - unlocks_inn_backroom.yml
  html/changelogs/furrycactus - wardens_tweak.yml
Labels: Mapping, Balance

#183 Enables tiefling, half-orc
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
  code/modules/jobs/job_types/roguetown/adventurer/pilgrim.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/monk.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/necromancer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/sorceress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/drunkard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/minstrel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/noble.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/peasant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/tbutcher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/thug.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
  html/changelogs/example copy.yml
Labels: Balance

#185 Katholikos and Inquisition Job Tweaks
  _maps/map_files/domotan/domotan.dmm
  code/datums/gods/patrons/all_aspect.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/confessor.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  html/changelogs/furrycactus - katholikos_roles_update.yml
Labels: Mapping, Balance

#190 Adds Steppe Lancer class
  code/datums/gods/patrons/elemental_pantheon.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/mob/living/carbon/human/npc/searaider.dm
  html/changelogs/example.yml
Labels: Balance

#191 Ports shapeshift, ties it to druidic ability - Finished
  code/__DEFINES/components.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/simple_animal/rogue/creacher/cat.dm
  code/modules/spells/roguetown/acolyte/earth.dm
  html/changelogs/peppermint-ports_shape_shifting.yml
  roguetown.dme
Labels: Balance

#192 Scomstone Addition
  _maps/map_files/domotan/domotan.dmm
  html/changelogs/hepatica - scomstone_addition.yml
Labels: Mapping
