Repository Encore-Server/Encore.1, pull requests merged in 2025-06, with the labels that each got.

#319 Changes the level up icon
  code/datums/status_effects/rogue/roguebuff.dm
  html/changelogs/kyres1-level_up_icons.yml
  icons/ui/hud/screen_alert.dmi
Labels: Spriting

#320 Map Compression Update
  _maps/domotan.json
  _maps/map_files/domotan/depreciated/domotan.dmm
  _maps/map_files/domotan/depreciated/domotan_east.dmm
  _maps/map_files/domotan/depreciated/domotan_south.dmm
  _maps/map_files/domotan/depreciated/domotan_west.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_north.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/domotan/fort_hellwatch.dmm
  _maps/map_files/domotan/old_doma.dmm
  code/modules/roguetown/mapgen/beach.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  roguetown.dme
Labels: Mapping

#327 Katholikos Silver Equipment
  _maps/map_files/domotan/old_doma.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v3.dmm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/quiver.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/confessor.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  html/changelogs/furrycactus - silver_gear_stuff.yml
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/pants.dmi
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/ammo.dmi
  modular_azurepeak/code/modules/clothing/rogueclothes/hats.dm
Labels: Spriting, Mapping, Balance

#326 Tea Brewing
  code/datums/stress/positive_events.dm
  code/modules/farming/crafting_recipes.dm
  code/modules/farming/produce.dm
  code/modules/power/roguelighting.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  html/changelogs/furrycactus - tea_brewing.yml
  icons/roguetown/items/produce.dmi
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/raw/NeuFood_herbs.dm
  modular/Neu_Food/icons/food.dmi
  roguetown.dme
Labels: Spriting

#331 Misc. QoL Map Tweaks
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/domotan/old_doma.dmm
  html/changelogs/furrycactus - misc-map-tweaks.yml
Labels: Mapping
