Repository Encore-Server/Encore.1, pull requests merged in 2025-05, with the labels that each got.

#292 Mining Tunnels Dungeon Fix
  _maps/map_files/domotan/domotan.dmm
  html/changelogs/furrycactus - mine_tunnel_fixes.yml
Labels: Mapping

#294 Adds a dye station to the normal spawn boat.
  _maps/map_files/generic/CentCom.dmm
  html/changelogs/hocka-dyestationadditions.yml
Labels: Mapping

#296 Booze Rework
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/templates/beach/med_beach_goblin_fort.dmm
  _maps/map_files/templates/beach/med_beach_shack.dmm
  _maps/map_files/templates/beach/med_beach_shipwreck.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v3.dmm
  _maps/map_files/templates/snow/med_snow_cellar.dmm
  _maps/map_files/templates/snow/med_snow_lodge.dmm
  _maps/map_files/templates/snow/med_snow_moundhome.dmm
  _maps/map_files/templates/underground/med_cave_church.dmm
  _maps/map_files/templates/underground/med_cave_shack.dmm
  _maps/map_files/templates/underground/small_cave_cellar.dmm
  _maps/map_files/templates/underground/small_cave_shack.dmm
  _maps/map_files/templates/underground/small_cave_shipwreck.dmm
  _maps/map_files/templates/underground/small_cave_shipwreck2.dmm
  code/modules/cargo/packsrogue/alcohols.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/farming/crafting_recipes.dm
  code/modules/farming/fermenting_barrel.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  html/changelogs/furrycactus - booze_and_catholicism.yml
  icons/roguetown/clothing/onmob/rings.dmi
  icons/roguetown/clothing/rings.dmi
Labels: Spriting, Mapping, Balance

#299 Prideful Heir Skill Tweak
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  html/changelogs/furrycactus - shirleigh-skill-tweak.yml
Labels: Balance

#300 v2.0.2
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/templates/beach/med_beach_goblin_fort.dmm
  _maps/map_files/templates/beach/med_beach_shack.dmm
  _maps/map_files/templates/beach/med_beach_shipwreck.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v3.dmm
  _maps/map_files/templates/snow/med_snow_cellar.dmm
  _maps/map_files/templates/snow/med_snow_lodge.dmm
  _maps/map_files/templates/snow/med_snow_moundhome.dmm
  _maps/map_files/templates/underground/med_cave_church.dmm
  _maps/map_files/templates/underground/med_cave_shack.dmm
  _maps/map_files/templates/underground/small_cave_cellar.dmm
  _maps/map_files/templates/underground/small_cave_shack.dmm
  _maps/map_files/templates/underground/small_cave_shipwreck.dmm
  _maps/map_files/templates/underground/small_cave_shipwreck2.dmm
  code/__DEFINES/font_changers.dm
  code/controllers/subsystem/shuttle.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/closed/wall/roguewalls.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/cargo/packsrogue/alcohols.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/farming/crafting_recipes.dm
  code/modules/farming/fermenting_barrel.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  html/changelogs/furrycactus - booze_and_catholicism.yml
  html/changelogs/furrycactus - mine_tunnel_fixes.yml
  html/changelogs/furrycactus - shirleigh-skill-tweak.yml
  html/changelogs/hocka-directnarratefix-i-pray.yml
  html/changelogs/hocka-dyestationadditions.yml
  html/changelogs/hocka-merchantfix.yml
  html/changelogs/kyres1-dice_rolling.yml
  html/changelogs/kyres1-smooth_operator_2.yml
  icons/roguetown/clothing/onmob/rings.dmi
  icons/roguetown/clothing/rings.dmi
  roguetown.dme
  sound/misc/fate_dice.ogg
  sound/misc/inspiration.ogg
  sound/misc/stinger.ogg
Labels: Spriting, Mapping, Balance

#308 Runtime fixes and more satanic double turf bullshit
  _maps/map_files/domotan/domotan_east.dmm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/greater_fiend.dm
  html/changelogs/kyres1-firedancer_fixes.yml
Labels: Mapping

#309 Adds a dungeon checkpoint spawn verb
  code/game/objects/structures/traveltile.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/event_verbs.dm
  html/changelogs/kyres1-checkpoints.yml
  icons/obj/structures/truetech.dmi
  roguetown.dme
Labels: Spriting

#310 Adds happy flowers yay and also Ents and fiend fixes
  _maps/map_files/domotan/domotan.dmm
  code/game/area/domotan/west.dm
  code/game/objects/structures/maneater.dm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/lesser_fiend.dm
  code/modules/mob/living/simple_animal/rogue/creacher/woodland.dm
  code/modules/roguetown/mapgen/beach.dm
  code/modules/roguetown/mapgen/bog.dm
  code/modules/roguetown/mapgen/decap.dm
  code/modules/roguetown/mapgen/east.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  html/changelogs/kyres1-mobs_and_flowers_yay.yml
  icons/mob/simple/ent.dmi
  roguetown.dme
Labels: Spriting, Mapping

#312 v2.0.3
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v3.dmm
  code/game/area/domotan/west.dm
  code/game/objects/structures/maneater.dm
  code/game/objects/structures/traveltile.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/event_verbs.dm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/greater_fiend.dm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/lesser_fiend.dm
  code/modules/mob/living/simple_animal/rogue/creacher/woodland.dm
  code/modules/roguetown/mapgen/beach.dm
  code/modules/roguetown/mapgen/bog.dm
  code/modules/roguetown/mapgen/decap.dm
  code/modules/roguetown/mapgen/east.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/mob/simple/ent.dmi
  icons/obj/structures/truetech.dmi
  roguetown.dme
Labels: Spriting, Mapping

#307 Necromancer Subclass for Bandit
  code/__DEFINES/traits.dm
  code/datums/stress/negative_events.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/necrolyte.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
  html/changelogs/furrycactus - necromancer_class.yml
  roguetown.dme
Labels: Balance

#314 Garrison Armoury Tweaks
  _maps/map_files/domotan/domotan.dmm
  html/changelogs/furrycactus - garrison_armoury_tweaks.yml
Labels: Mapping

#315 v2.0.4
  _maps/map_files/domotan/domotan.dmm
  code/__DEFINES/traits.dm
  code/datums/character_flaw/_character_flaw.dm
  code/datums/character_flaw/limbloss.dm
  code/datums/stress/negative_events.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/necrolyte.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  modular_azurepeak/code/game/objects/items/ritualcircles.dm
  roguetown.dme
Labels: Mapping, Balance
