Repository Encore-Server/Encore.1, pull requests merged in 2025-04, with the labels that each got.

#198 The Rise of the Iron Equipment Middle Class
  code/modules/cargo/packsrogue/Brigand.dm
  code/modules/cargo/packsrogue/Iconoclast.dm
  code/modules/cargo/packsrogue/Knight.dm
  code/modules/cargo/packsrogue/Sellsword.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/confessor.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/squireerrant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/other/deathknight.dm
  code/modules/jobs/job_types/roguetown/peasants/beggar.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/onmob/wrists.dmi
  icons/roguetown/clothing/pants.dmi
  icons/roguetown/clothing/wrists.dmi
  modular_azurepeak/code/modules/clothing/rogueclothes/hats.dm
  roguetown.dme
Labels: Spriting, Balance

#197 The Great Spell Portening Begins
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/mindlink.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/negative_events.dm
  code/game/objects/structures.dm
  code/modules/antagonists/roguetown/villain/vampire.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/spells/roguetown/acolyte/earth.dm
  code/modules/spells/roguetown/acolyte/illusion.dm
  code/modules/spells/roguetown/acolyte/other.dm
  code/modules/spells/roguetown/acolyte/protection.dm
  code/modules/spells/roguetown/buffs.dm
  code/modules/spells/roguetown/wizard.dm
  html/changelogs/peppermint-spell_aditions.yml
  icons/mob/actions/roguespells.dmi
  modular/code/modules/living/carbon/stress.dm
  modular_azurepeak/virtues/size.dm
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  roguetown.dme
  sound/magic/blink.ogg
  sound/magic/gravity.ogg
  sound/magic/magearmordown.ogg
  sound/magic/magearmorup.ogg
  sound/magic/mockery.ogg
  sound/magic/unmagnet.ogg
Labels: Spriting, Balance

#201 Seals off Hell (again)
  _maps/map_files/domotan/domotan_east.dmm
  html/changelogs/furrycactus - mt_miracle_constipation.yml
Labels: Mapping

#209 Jb implement git hook to process changelog
  .github/workflows/encore_process_changelog.yml
  tools/encore_changelog.py
  tools/ss13_genchangelog.py
Labels: documentation

#212 Jb implement git hook to process changelog
  .github/workflows/encore_process_changelog.yml
  html/changelogs/doxxmedearly - fishingstuff.yml
  html/changelogs/doxxmedearly - guidancefortfix.yml
  html/changelogs/doxxmedearly - holyspell_relocation.yml
  html/changelogs/doxxmedearly - invistipfixes.yml
  html/changelogs/doxxmedearly - knighttitles.yml
  html/changelogs/doxxmedearly - prostheticlegs.yml
  html/changelogs/doxxmedearly - spellbugfixes.yml
  html/changelogs/doxxmedearly - stockpile.yml
  html/changelogs/doxxmedearly - stopschainpuking.yml
  tools/encore_changelog.py
Labels: documentation

#215 update directory
  .github/workflows/encore_process_changelog.yml
Labels: documentation

#217 Update permissions
  .github/workflows/encore_process_changelog.yml
Labels: documentation

#203 Turf color adjustments, new sand, stone windows, tents
  code/game/objects/structures/roguetown/edges.dm
  code/game/turfs/closed/wall/roguewalls.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/game/turfs/open/water.dm
  icons/roguetown/items/natural.dmi
  icons/roguetown/misc/foliagetall.dmi
  icons/turf/edges/natural.dmi
  icons/turf/edges/stone.dmi
  icons/turf/roguefloor.dmi
  icons/turf/roguewall.dmi
  icons/turf/sand.dmi
  roguetown.dme
Labels: Spriting, Mapping

#227 Roof RuntimeFix
  _maps/templates/template_helpers.dm
  html/changelogs/example copy.yml
Labels: Mapping

#229 More templates and gameplay variation, runtime fixes
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/templates/snow/med_snow_crypt.dmm
  _maps/map_files/templates/underground/med_cave_church.dmm
  _maps/map_files/templates/underground/med_cave_crypt.dmm
  _maps/map_files/templates/underground/med_cave_deposit_high.dmm
  _maps/map_files/templates/underground/med_cave_deposit_med.dmm
  _maps/map_files/templates/underground/med_cave_deposit_salt.dmm
  _maps/map_files/templates/underground/med_cave_deposit_scarce.dmm
  _maps/map_files/templates/underground/med_cave_effigy.dmm
  _maps/map_files/templates/underground/med_cave_hive.dmm
  _maps/map_files/templates/underground/med_cave_lake.dmm
  _maps/map_files/templates/underground/med_cave_lodge.dmm
  _maps/map_files/templates/underground/med_cave_orrery.dmm
  _maps/map_files/templates/underground/med_cave_pond.dmm
  _maps/map_files/templates/underground/med_cave_tomb.dmm
  _maps/templates/template_helpers.dm
  _maps/templates/underground.dm
  code/controllers/subsystem/mapping.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/spawners/traps.dm
  code/game/objects/structures/traps.dm
  html/changelogs/kyres1-mapping_finalization.yml
  icons/roguetown/items/traps.dmi
Labels: Spriting, Mapping

#235 Fixes the testing map to save developer lives
  _maps/map_files/roguetest/roguetest.dmm
  _maps/roguetest.json
  code/rt.dm
  code/testing.dm
Labels: Mapping

#206 Witch Wednesday Buffs - Finished
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/__DEFINES/traits.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/datums/skills/magic.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/positive_events.dm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/roguetown/adventurer/witch.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/carbon.dm
  icons/roguetown/misc/rituals.dmi
  modular_azurepeak/code/game/objects/items/ritechalk.dm
  modular_azurepeak/code/game/objects/items/ritualcircles.dm
  modular_azurepeak/virtues/utility.dm
  roguetown.dme
Labels: Spriting, Balance

#189 Hostile mobs and early demons
  code/__DEFINES/mobs.dm
  code/__DEFINES/roguetown.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/mob/living/carbon/human/npc/demon.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  code/modules/mob/living/carbon/human/voicepacks/other/demon.dm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/demons.dm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/greater_fiend.dm
  code/modules/mob/living/simple_animal/rogue/creacher/hell/lesser_fiend.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/roguetown/mob/monster/demon_fm.dmi
  icons/roguetown/mob/monster/demon_mt.dmi
  icons/roguetown/mob/monster/hell/48x48.dmi
  icons/roguetown/mob/monster/hell/96x96.dmi
  icons/roguetown/mob/monster/hell/fiends.dmi
  modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/newminotaur.dm
  roguetown.dme
  sound/vo/mobs/demon/demon_growl.ogg
  sound/vo/mobs/demon/demon_hiss.ogg
  sound/vo/mobs/demon/demon_laughter.ogg
  sound/vo/mobs/demon/demon_pain.ogg
  sound/vo/mobs/demon/demon_roar.ogg
  strings/rt/npc/demonaggro.txt
  strings/rt/npc/demonlines.txt
Labels: help wanted, Spriting, coding, content

#205 Spell and Gear Reassignment
  _maps/map_files/domotan/domotan.dmm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/gods/patrons/all_aspect.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/datums/gods/patrons/heretic.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/confessor.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/spells/roguetown/acolyte/other.dm
  code/rt.dm
  html/changelogs/furrycactus - spell_and_gear_assignment_overhaul.yml
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
Labels: Mapping, Balance

#237 Adds 46 dungeons
  _maps/map_files/templates/underground/med_cave_pond.dmm
  _maps/map_files/templates/underground/small_cave_armory.dmm
  _maps/map_files/templates/underground/small_cave_armory2.dmm
  _maps/map_files/templates/underground/small_cave_cargo.dmm
  _maps/map_files/templates/underground/small_cave_cargo2.dmm
  _maps/map_files/templates/underground/small_cave_crater.dmm
  _maps/map_files/templates/underground/small_cave_crater2.dmm
  _maps/map_files/templates/underground/small_cave_deposit_gems.dmm
  _maps/map_files/templates/underground/small_cave_fishingshack.dmm
  _maps/map_files/templates/underground/small_cave_fishingshack2.dmm
  _maps/map_files/templates/underground/small_cave_garrison.dmm
  _maps/map_files/templates/underground/small_cave_heresy.dmm
  _maps/map_files/templates/underground/small_cave_loot.dmm
  _maps/map_files/templates/underground/small_cave_loot2.dmm
  _maps/map_files/templates/underground/small_cave_loot2_bad.dmm
  _maps/map_files/templates/underground/small_cave_loot3.dmm
  _maps/map_files/templates/underground/small_cave_loot3_bad.dmm
  _maps/map_files/templates/underground/small_cave_loot_bad.dmm
  _maps/map_files/templates/underground/small_cave_lostworld.dmm
  _maps/map_files/templates/underground/small_cave_lostworld2.dmm
  _maps/map_files/templates/underground/small_cave_lostworld3.dmm
  _maps/map_files/templates/underground/small_cave_orc_camp.dmm
  _maps/map_files/templates/underground/small_cave_pit.dmm
  _maps/map_files/templates/underground/small_cave_pit2.dmm
  _maps/map_files/templates/underground/small_cave_prison.dmm
  _maps/map_files/templates/underground/small_cave_sewer.dmm
  _maps/map_files/templates/underground/small_cave_sewer2.dmm
  _maps/map_files/templates/underground/small_cave_sewer3.dmm
  _maps/map_files/templates/underground/small_cave_sewer4.dmm
  _maps/map_files/templates/underground/small_cave_sewer5.dmm
  _maps/map_files/templates/underground/small_cave_shipwreck.dmm
  _maps/map_files/templates/underground/small_cave_shipwreck2.dmm
  _maps/map_files/templates/underground/small_cave_temptation.dmm
  _maps/map_files/templates/underground/small_cave_trollden.dmm
  _maps/map_files/templates/underground/small_cave_volcanic.dmm
  _maps/map_files/templates/underground/small_cave_volcanic2.dmm
  _maps/map_files/templates/underground/small_cave_volcanic3.dmm
  _maps/map_files/templates/underground/small_cave_volcanic4.dmm
  _maps/map_files/templates/underground/small_cave_whirlpool.dmm
  _maps/map_files/templates/underground/small_cave_wolfden.dmm
  _maps/map_files/templates/underground/small_cave_wolfden2.dmm
  _maps/map_files/templates/underground/small_cave_wolfden3.dmm
  _maps/templates/underground.dm
  code/game/objects/effects/spawners/roguemapgen.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  html/changelogs/example copy.yml
  html/changelogs/kyres1-MOAR_DUNGEONS.yml
Labels: Mapping

#228 Resprites roguetown machines, makes shirts less chesty
  _maps/map_files/domotan/domotan.dmm
  code/modules/roguetown/roguemachine/ATM.dm
  code/modules/roguetown/roguemachine/mail.dm
  code/modules/roguetown/roguemachine/merchant.dm
  code/modules/roguetown/roguemachine/scomm.dm
  code/modules/roguetown/roguemachine/steward.dm
  code/modules/roguetown/roguemachine/stockpile.dm
  code/modules/roguetown/roguemachine/vendor.dm
  code/modules/roguetown/roguemachine/withdraw.dm
  html/changelogs/4-9-2025-kyres1_machines.yml
  icons/ass/assalien.png
  icons/ass/assdrone.png
  icons/ass/assfemale.png
  icons/ass/assmale.png
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/items/lighting.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/misc/lighting.dmi
  icons/roguetown/misc/machines.dmi
Labels: Spriting, Mapping

#238 Adds MORE templates
  _maps/map_files/templates/beach/small_beach_lobster_den.dmm
  _maps/map_files/templates/beach/small_beach_oasis.dmm
  _maps/map_files/templates/forest/med_forest_caveshelter.dmm
  _maps/map_files/templates/forest/med_forest_wolfden.dmm
  _maps/map_files/templates/forest/small_forest_bog.dmm
  _maps/map_files/templates/forest/small_forest_camp.dmm
  _maps/map_files/templates/forest/small_forest_crabs.dmm
  _maps/map_files/templates/forest/small_forest_farm.dmm
  _maps/map_files/templates/forest/small_forest_quarry.dmm
  _maps/map_files/templates/forest/small_forest_stream.dmm
  _maps/map_files/templates/forest/small_forest_wolfden.dmm
  _maps/map_files/templates/mountain/med_mountain_caveshelter.dmm
  _maps/map_files/templates/mountain/med_mountain_wolfden.dmm
  _maps/map_files/templates/mountain/small_mountain_bog.dmm
  _maps/map_files/templates/mountain/small_mountain_camp.dmm
  _maps/map_files/templates/mountain/small_mountain_farm.dmm
  _maps/map_files/templates/mountain/small_mountain_quarry.dmm
  _maps/map_files/templates/mountain/small_mountain_stream.dmm
  _maps/map_files/templates/mountain/small_mountain_wolfden.dmm
  _maps/templates/beach.dm
  _maps/templates/forest.dm
  _maps/templates/mountain.dm
  html/changelogs/kyres1-mapping_morrrre.yml
Labels: Mapping

#245 fixes some templates
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/templates/underground.dm
  html/changelogs/kyres1-template_fixes_again.yml
Labels: Mapping

#247 Final revisions for pre-release
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/templates/underground.dm
  code/rt.dm
  html/changelogs/4-11-2025-fixes_testing_mode.yml
  html/changelogs/kyres1-template_fixes_again.yml
Labels: Mapping

#248 Fort Hellwatch Randomised Templates
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z1/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q4_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v3.dmm
  html/changelogs/furrycactus - hellwatch_random_templates.yml
Labels: Mapping

#249 Last Minute Witch Fixes
  code/modules/jobs/job_types/roguetown/adventurer/witch.dm
  html/changelogs/furrycactus - last_minute_witch_fixes.yml
Labels: Balance

#250 Lancer resprites the throne gate and machines
  _maps/map_files/domotan/domotan.dmm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  html/changelogs/kyres1-lancer_resprites.yml
  icons/roguetown/misc/gate.dmi
  icons/roguetown/misc/machines.dmi
Labels: Spriting, Mapping

#251 Hellwatch, sprites and fixes for 2.0
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z1/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q4_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v3.dmm
  code/modules/jobs/job_types/roguetown/adventurer/witch.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  html/changelogs/furrycactus - hellwatch_random_templates.yml
  html/changelogs/furrycactus - last_minute_witch_fixes.yml
  html/changelogs/kyres1-lancer_resprites.yml
  icons/roguetown/misc/gate.dmi
  icons/roguetown/misc/machines.dmi
Labels: Spriting, Mapping, Balance

#256 Fixes the hive and the machine sprites
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/templates/underground/med_cave_hive.dmm
  icons/roguetown/misc/machines.dmi
Labels: Spriting, Mapping

#258 New title screen
  html/changelogs/kyres1-new_fancy_title.yml
  icons/ui/title/default_title.dmi
Labels: Spriting

#266 Ranger-Knight Subclass Fix
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  html/changelogs/furrycactus - ranger_knight_fix.yml
Labels: Balance

#273 Adds the Shapeshifting Skill to Gani and Secret God Clerics/Witches
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/witch.dm
  html/changelogs/furrycactus - small_shapeshifting_fixes.yml
Labels: Balance

#274 Acolyte Job Overhaul
  code/modules/jobs/job_types/roguetown/church/monk.dm
  html/changelogs/furrycactus - acolyte_overhaul.yml
Labels: Balance

#280 Yet Another Fort Hellwatch Tweak
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/templates/hellwatch/z1/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z1/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z1/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q2_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v1.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v2.dmm
  _maps/map_files/templates/hellwatch/z2/q4_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q1_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q2_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v1.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v2.dmm
  _maps/map_files/templates/hellwatch/z3/q3_v3.dmm
  _maps/map_files/templates/hellwatch/z3/q4_v1.dmm
  html/changelogs/furrycactus - more_hellwatch_suffering.yml
Labels: Mapping

#281 Panther Warden Subclass
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  html/changelogs/furrycactus - panther_warden.yml
Labels: Balance

#282 Some New Music
  _maps/map_files/domotan/domotan.dmm
  code/game/area/roguetownareas.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  html/changelogs/furrycactus - some_new_tracks.yml
  sound/music/area/creepy_woods.ogg
  sound/music/area/shirleigh_keep.ogg
  sound/music/combat_templar.ogg
  sound/music/credits.txt
Labels: Mapping, Balance

#285 Fixes conflicts for domotan north
  _maps/map_files/domotan/domotan.dmm
Labels: Mapping

#284 Adds Tutorial Island
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/area/roguetownareas.dm
  html/changelogs/kyres1-tutorial_island.yml
Labels: Mapping
