Repository Encore-Server/Encore.1, pull requests merged in 2025-02, with the labels that each got.

#21 Remaps the town
  _maps/map_files/domotan/domotan.dmm
  code/game/objects/structures/walldeco.dm
  icons/roguetown/misc/96x96.dmi
  icons/roguetown/misc/decoration.dmi
Labels: Spriting, Mapping

#14 Bone needles and arrows
  code/game/objects/items/rogueitems/needle.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/modules/roguetown/roguecrafting/items.dm
  html/changelogs/doxxmedearly - bonearrows.yml
  icons/roguetown/weapons/ammo.dmi
Labels: Spriting

#26 merges fix into release
  _maps/map_files/domotan/domotan.dmm
Labels: Mapping

#29 Map tweaks for manor and addressing remap feedback
  _maps/map_files/domotan/domotan.dmm
Labels: Mapping

#30 v1.0.1
  _maps/map_files/domotan/domotan.dmm
  code/modules/roguetown/roguemachine/vendor.dm
Labels: Mapping

#31 returns the slab
  _maps/map_files/domotan/domotan.dmm
Labels: Mapping

#33 Fast forward pre-release to master
  _maps/map_files/domotan/domotan.dmm
  code/modules/roguetown/roguemachine/vendor.dm
Labels: Mapping

#37 Old doma fixes and additions
  _maps/map_files/domotan/domotan.dmm
  icons/roguetown/misc/256.dmi
  roguetown.dme
Labels: Spriting, Mapping

#38 v1.0.2
  _maps/map_files/domotan/domotan.dmm
  code/__DEFINES/tgs.config.dm
  code/__DEFINES/tgs.dm
  code/game/objects/items/rogueitems/bait.dm
  code/game/world.dm
  code/modules/client/client_procs.dm
  code/modules/roguetown/roguestock/stockpile.dm
  code/modules/tgs/LICENSE
  code/modules/tgs/README.md
  code/modules/tgs/core/README.md
  code/modules/tgs/core/byond_world_export.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
  html/changelogs/doxxmedearly - stockpile.yml
  html/changelogs/hocka-betterbait.yml
  icons/roguetown/misc/256.dmi
Labels: Spriting, Mapping

#48 Ranger-Zealot, Scout-Templar & Ranger-Knight
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  html/changelogs/hocka-rangerknight.yml
Labels: Balance

#46 Fishing bugfixes
  code/modules/mob/living/simple_animal/rogue/creacher/mudcrab.dm
  icons/mob/animal.dmi
  modular/Neu_Food/code/raw/NeuFood_meat.dm
Labels: Spriting

#49 Third slot, race selection, bugfixes, misc. tweaks
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/rogue/devotion.dm
  code/game/objects/items/rogueitems/books.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/client/preferences.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
  code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
  code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/spells/spell_types/explosion.dm
  icons/turf/roguefloor.dmi
  sound/magic/distant_explosion.ogg
  sound/magic/distant_explosion_huge.ogg
Labels: Spriting

#50 v1.0.4
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/rogue/devotion.dm
  code/game/objects/items/rogueitems/books.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/client/preferences.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
  code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
  code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mudcrab.dm
  code/modules/spells/spell_types/explosion.dm
  html/changelogs/hocka-rangerknight.yml
  icons/mob/animal.dmi
  icons/turf/roguefloor.dmi
  modular/Neu_Food/code/raw/NeuFood_meat.dm
  sound/magic/distant_explosion.ogg
  sound/magic/distant_explosion_huge.ogg
Labels: Spriting, Balance

#73 Changes how Ranger-Knight type classes are given their equipment
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  html/changelogs/hocka-rangerfix.yml
Labels: Balance

#80 Opens Western Domotan
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/area/domotan/west.dm
  code/game/area/roguetownareas.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  roguetown.dme
Labels: Mapping

#82 Weeping wood changelog because I forgot
  _maps/map_files/generic/CentCom.dmm
  html/changelogs/kyres1-weepingwood_and_friends.yml
Labels: Mapping

#83 v1.0.5
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_east.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/generic/CentCom.dmm
  code/_onclick/hud/screen_objects.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/game/area/domotan/west.dm
  code/game/area/roguetownareas.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguejobs/fisher/fish.dm
  code/modules/roguetown/roguemachine/_withdraw_tab.dm
  code/modules/roguetown/roguestock/_roguestock.dm
  code/modules/roguetown/roguestock/stockpile.dm
  html/changelogs/doxxmedearly - chathelp.yml
  html/changelogs/hocka-oatbait.yml
  html/changelogs/hocka-rangerfix.yml
  html/changelogs/kyres1-weepingwood_and_friends.yml
  interface/interface.dm
  roguetown.dme
  sound/music/area/sleeping.ogg
Labels: Mapping, Balance

#89 weeping wood fixes #4
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/domotan/domotan_west.dmm
  code/game/area/domotan/west.dm
  code/modules/roguetown/mapgen/forest.dm
Labels: Mapping

#91 v1.0.6
  _maps/map_files/domotan/domotan_south.dmm
  _maps/map_files/domotan/domotan_west.dmm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/gods/_patron.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/game/area/domotan/west.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/explosion.dm
  html/changelogs/doxxmedearly - spellbugfixes.yml
Labels: Mapping

#95 Changes the end title and credits music
  icons/fullblack.dmi
  sound/music/credits.ogg
Labels: Spriting

#97 Gives and takes Miracles, removes call of Gani
  code/controllers/subsystem/rogue/devotion.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  html/changelogs/doxxmedearly - holyspell_relocation.yml
Labels: Balance

#99 Ranger Tracking Buff
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  html/changelogs/peppermint - rangerbuff.yml
Labels: Balance

#100 Templar Weapon Selection Additions
  code/modules/jobs/job_types/roguetown/church/templar.dm
  html/changelogs/furrycactus - templar_weapons.yml
Labels: Balance

#109 Tweaks and fixes
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_west.dmm
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  modular_azurepeak/code/modules/clothing/rogueclothes/hats.dm
  modular_azurepeak/code/modules/spells/pantheon/divine/necra.dm
  sound/misc/mat/end.ogg
  sound/misc/mat/endin.ogg
  sound/misc/mat/endout.ogg
  sound/misc/mat/fap.ogg
  sound/misc/mat/fingering.ogg
  sound/misc/mat/girlmouth (1).ogg
  sound/misc/mat/girlmouth (2).ogg
  sound/misc/mat/guymouth (1).ogg
  sound/misc/mat/guymouth (2).ogg
  sound/misc/mat/guymouth (3).ogg
  sound/misc/mat/guymouth (4).ogg
  sound/misc/mat/guymouth (5).ogg
  sound/misc/mat/insert (1).ogg
  sound/misc/mat/insert (2).ogg
  sound/misc/mat/mouthend (1).ogg
  sound/misc/mat/mouthend (2).ogg
  sound/misc/mat/segso.ogg
Labels: Mapping, Balance

#110 v1.0.7
  _maps/map_files/domotan/domotan.dmm
  _maps/map_files/domotan/domotan_west.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/character_flaw/_character_flaw.dm
  code/datums/gods/patrons/elemental_pantheon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
  code/modules/spells/roguetown/acolyte/illusion.dm
  code/modules/spells/roguetown/necromancer.dm
  code/modules/spells/roguetown/spider.dm
  html/changelogs/doxxmedearly - holyspell_relocation.yml
  html/changelogs/doxxmedearly - invistipfixes.yml
  html/changelogs/furrycactus - beespider_honey_butchering.yml
  html/changelogs/furrycactus - heretical_spells.yml
  html/changelogs/furrycactus - mjallidhorn_miracle_tweak.yml
  html/changelogs/furrycactus - spawn_boat_clock.yml
  html/changelogs/furrycactus - templar_weapons.yml
  html/changelogs/peppermint - rangerbuff.yml
  icons/fullblack.dmi
  modular_azurepeak/code/modules/clothing/rogueclothes/hats.dm
  modular_azurepeak/code/modules/spells/pantheon/divine/necra.dm
  modular_azurepeak/virtues/size.dm
  sound/misc/mat/end.ogg
  sound/misc/mat/endin.ogg
  sound/misc/mat/endout.ogg
  sound/misc/mat/fap.ogg
  sound/misc/mat/fingering.ogg
  sound/misc/mat/girlmouth (1).ogg
  sound/misc/mat/girlmouth (2).ogg
  sound/misc/mat/guymouth (1).ogg
  sound/misc/mat/guymouth (2).ogg
  sound/misc/mat/guymouth (3).ogg
  sound/misc/mat/guymouth (4).ogg
  sound/misc/mat/guymouth (5).ogg
  sound/misc/mat/insert (1).ogg
  sound/misc/mat/insert (2).ogg
  sound/misc/mat/mouthend (1).ogg
  sound/misc/mat/mouthend (2).ogg
  sound/misc/mat/segso.ogg
  sound/music/credits.ogg
Labels: Spriting, Mapping, Balance

#112 Templar Polearm Skill Fix
  code/modules/jobs/job_types/roguetown/church/templar.dm
  html/changelogs/furrycactus - templar_lucerne_skill_fix.yml
Labels: Balance

#113 Some Inn fixes (plus a minor manor fix)
  _maps/map_files/domotan/domotan.dmm
  code/game/objects/items/rogueitems/keyrings.dm
Labels: Mapping

#114 Elemental Tabard Fixes
  _maps/map_files/domotan/domotan.dmm
  code/modules/clothing/rogueclothes/cloaks.dm
  html/changelogs/furrycactus - elemental_tabard_fixes.yml
Labels: Mapping

#115 Gives priest the necklace that matches their faith on spawn.
  code/modules/jobs/job_types/roguetown/church/priest.dm
Labels: Balance

#116 Gives the Priest a room
  _maps/map_files/domotan/domotan.dmm
Labels: Mapping

#118 Give Court Magicians a new staff
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/roguetown/roguecrafting/items.dm
  icons/roguetown/weapons/64.dmi
Labels: Spriting, Balance

#119 Druid House Upgrade
  _maps/map_files/domotan/domotan.dmm
  html/changelogs/peppermint-druidhouse.yml
Labels: Mapping

#120 Adds prosthetic legs
  code/datums/character_flaw/_character_flaw.dm
  code/datums/character_flaw/limbloss.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm
  code/modules/roguetown/roguejobs/engineer/prosthetics.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  code/modules/surgery/bodyparts/helpers.dm
  code/modules/surgery/surgeries/prosthetic_replacement.dm
  html/changelogs/doxxmedearly - prostheticlegs.yml
  icons/mob/species/anthro_small_female.dmi
  icons/mob/species/anthro_small_male.dmi
  icons/mob/species/moth_f.dmi
  icons/mob/species/moth_m.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/mob/bodies/f/fd.dmi
  icons/roguetown/mob/bodies/f/fds.dmi
  icons/roguetown/mob/bodies/f/fm.dmi
  icons/roguetown/mob/bodies/f/fo.dmi
  icons/roguetown/mob/bodies/f/fos.dmi
  icons/roguetown/mob/bodies/f/fs.dmi
  icons/roguetown/mob/bodies/f/ft.dmi
  icons/roguetown/mob/bodies/f/ft_muscular.dmi
  icons/roguetown/mob/bodies/m/ma.dmi
  icons/roguetown/mob/bodies/m/md.dmi
  icons/roguetown/mob/bodies/m/mds.dmi
  icons/roguetown/mob/bodies/m/mem.dmi
  icons/roguetown/mob/bodies/m/met.dmi
  icons/roguetown/mob/bodies/m/mets.dmi
  icons/roguetown/mob/bodies/m/mg.dmi
  icons/roguetown/mob/bodies/m/mm.dmi
  icons/roguetown/mob/bodies/m/mo.dmi
  icons/roguetown/mob/bodies/m/mos.dmi
  icons/roguetown/mob/bodies/m/ms.dmi
  icons/roguetown/mob/bodies/m/mt.dmi
  icons/roguetown/mob/bodies/m/mt_muscular.dmi
  icons/roguetown/mob/bodies/m/mts.dmi
  modular_hearthstone/code/game/objects/effects/track.dm
  roguetown.dme
Labels: Spriting

#121 Katholikos Banners
  _maps/map_files/domotan/domotan.dmm
  code/game/objects/structures/walldeco.dm
  html/changelogs/furrycactus - elemental_banners.yml
  icons/roguetown/misc/decoration.dmi
  modular_hearthstone/code/game/objects/structures/hangingbanners.dm
  modular_hearthstone/icons/obj/decor.dmi
Labels: Spriting, Mapping

#124 druid treehouse fixes
  _maps/map_files/domotan/domotan.dmm
  icons/turf/roguefloor.dmi
Labels: Spriting, Mapping
